spring:
  aop:
    proxyTargetClass: true
  application:
    name: web-admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
        packageScan: com.lanshan.web.admin.model
        ddl-auto: none
  jta:
     transaction-manager-id: transactionManager        
  datasource:
      url: jdbc:mysql://47.98.217.126:3306/lsims?useUnicode=true&characterEncoding=UTF-8
      username: lsims
      password: lsims
      driver-class-name: com.mysql.jdbc.Driver  
  redis:
    host: 47.98.217.126
    port: 6379
    password: trAns59988 
  profiles:
    active: dev  

server:
  port: 8080
  maxHttpHeaderSize: 10240000
  tomcat:
    uri-encoding: UTF-8
    maxHttpHeaderSize: 10240000
    maxHttpPostSize: 10240000
  servlet:
    context-path: /web-admin
    session:
      timeout: 360000  

eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
  server:
    enable-self-preservation: false  #关闭eureka自我保护,生产环境不建议关闭自我保护

#认证中心index页面地址,如果直接登录认证中心则会跳转到该地址
uaa.server.index-path: /uaa/index
#认证中心跳转路径前缀
uaa.server.service.path: /uaa/**
#不走认证的url集合
http.authorize.matchers: /**/css/**,/**/styles/**,/**/js/**,/**/plugin/**,/**/plugins/**,/**/template/**,/**/img/**,/**/fonts/**,/**/cvr100u/**,/css/**,/js/**,/plugin/**,/template/**,/img/**,/fonts/**,/cvr100u/**

zuul:
  routes:
    uaa-server:
      sensitiveHeaders: "*"
      path: ${uaa.server.service.path}
      stripPrefix: false
  add-proxy-headers: true

security:
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://127.0.0.1:9060/uaa/oauth/token
      userAuthorizationUri: http://127.0.0.1:9060/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource


