package com.lanshan.web.admin.model;
// Generated 2018-8-31 17:52:25 by Hibernate Tools 5.2.3.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * SmPreferences generated by hbm2java
 */
@Entity
@Table(name = "sm_region", catalog = "lsims")
public class SmRegion implements java.io.Serializable {

	private Integer id;
	private String regionName;
	private Integer parentId;
	private String regionType;
	private String regionCode;
	private SmRegion parent;
	private Date createDate;
	private List childs = null;

	@Column(name = "CREATE_DATE_")
	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "REGION_NAME", length = 120)
	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@Column(name = "PARENT_ID")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "REGION_TYPE", length = 10)
	public String getRegionType() {
		return this.regionType;
	}

	public void setRegionType(String regionType) {
		this.regionType = regionType;
	}

	@Column(name = "REGION_CODE", length = 10)
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Transient
	public SmRegion getParent() {
		return parent;
	}

	public void setParent(SmRegion parent) {
		this.parent = parent;
	}

	@Transient
	public List getChilds() {
		return childs;
	}

	public void setChilds(List childs) {
		this.childs = childs;
	}

}
