package com.lanshan.web.admin.model;
// Generated 2018-9-21 17:47:51 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmRoleComponent generated by hbm2java
 */
@Entity
@Table(name = "sm_role_component", catalog = "lsims")
public class SmRoleComponent implements java.io.Serializable {

	private Integer id;
	private Integer urlId;
	private Integer componentId;
	private Integer roleId;
	private Date createDate;
	private String systemId;

	public SmRoleComponent() {
	}

	public SmRoleComponent(Integer urlId, Integer componentId, Integer roleId, Date createDate, String systemId) {
		this.urlId = urlId;
		this.componentId = componentId;
		this.roleId = roleId;
		this.createDate = createDate;
		this.systemId = systemId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "URL_ID_")
	public Integer getUrlId() {
		return this.urlId;
	}

	public void setUrlId(Integer urlId) {
		this.urlId = urlId;
	}

	@Column(name = "COMPONENT_ID_")
	public Integer getComponentId() {
		return this.componentId;
	}

	public void setComponentId(Integer componentId) {
		this.componentId = componentId;
	}

	@Column(name = "ROLE_ID_")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE_", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "SYSTEM_ID", length = 60)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

}
