package com.lanshan.web.admin.model;
// Generated 2018-9-18 17:05:29 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SmUrlComponent generated by hbm2java
 */
@Entity
@Table(name = "sm_url_component", catalog = "lsims")
public class SmUrlComponent implements java.io.Serializable {

	private Integer id;
	private Integer roleId;
	private Integer urlId;
	private Date createDate;
	private String lastUpdatePerson;
	private Date lastUpdateTime;
	private String systemId;

	public SmUrlComponent() {
	}

	public SmUrlComponent(Integer roleId, Integer urlId, Date createDate, String lastUpdatePerson, Date lastUpdateTime,
			String systemId) {
		this.roleId = roleId;
		this.urlId = urlId;
		this.createDate = createDate;
		this.lastUpdatePerson = lastUpdatePerson;
		this.lastUpdateTime = lastUpdateTime;
		this.systemId = systemId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ROLE_ID_")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "URL_ID_")
	public Integer getUrlId() {
		return this.urlId;
	}

	public void setUrlId(Integer urlId) {
		this.urlId = urlId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE_", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "LAST_UPDATE_PERSON", length = 32)
	public String getLastUpdatePerson() {
		return this.lastUpdatePerson;
	}

	public void setLastUpdatePerson(String lastUpdatePerson) {
		this.lastUpdatePerson = lastUpdatePerson;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATE_TIME", length = 19)
	public Date getLastUpdateTime() {
		return this.lastUpdateTime;
	}

	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	@Column(name = "SYSTEM_ID_", length = 60)
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

}
